// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_A10Kl0iAnTQuOhFvtgXoffx0QnIMLwo',
    appId: '1:307411138390:web:55d49f95961d6fffb2c8f7',
    messagingSenderId: '307411138390',
    projectId: 'quotes-db-9c512',
    authDomain: 'quotes-db-9c512.firebaseapp.com',
    storageBucket: 'quotes-db-9c512.appspot.com',
    measurementId: 'G-T0B91NDBP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEpDAk1bJVC55Z-zzAfjQj_o1Jv4CtHTk',
    appId: '1:307411138390:android:a5b0042a3844f393b2c8f7',
    messagingSenderId: '307411138390',
    projectId: 'quotes-db-9c512',
    storageBucket: 'quotes-db-9c512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPtvOAgu9y7B3FhPYVdL4MFSf90tEolgk',
    appId: '1:307411138390:ios:cb9df76d66ea2a50b2c8f7',
    messagingSenderId: '307411138390',
    projectId: 'quotes-db-9c512',
    storageBucket: 'quotes-db-9c512.appspot.com',
    iosClientId: '307411138390-unnt9tocjsom9cemt4oubot28nctsiuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.devopsAsgnmtGroup3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPtvOAgu9y7B3FhPYVdL4MFSf90tEolgk',
    appId: '1:307411138390:ios:cb9df76d66ea2a50b2c8f7',
    messagingSenderId: '307411138390',
    projectId: 'quotes-db-9c512',
    storageBucket: 'quotes-db-9c512.appspot.com',
    iosClientId: '307411138390-unnt9tocjsom9cemt4oubot28nctsiuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.devopsAsgnmtGroup3',
  );
}
